version: "0.1"

services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     CLOUDINARY_NAME: ${CLOUDINARY_NAME}
  #     CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
  #     CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

  #   ports:
  #     - "8000:8000"

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
